security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        memory_provider:
            memory:
                users:
                    admin: { password: '$2y$10$AAlfx5lSJEW2lOpUGIHPIOejeWtWTadnmjYjHJr.2Ks2AexM9Hhcq', roles: ['ROLE_ADMIN'] }
                    manager: { password: '$2y$10$I3eYWxAzfaFJCYIBMoKA/e4IGGa6jqGUk1B6GHXwEBfFyfnjpCB96', roles: ['ROLE_MANAGER'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: memory_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
